<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Agentics.Extensions.Aspire.AzureResourceManager</PackageId>
    <Description>Extensible, API-version-aware Azure Resource Manager provider emulator for Aspire.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" Version="13.4.6" />
    <ProjectReference Include="../Aspire.Hosting.MicrosoftTenant/Aspire.Hosting.MicrosoftTenant.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
